### PR TITLE
Add Linux portability test on GitHub Actions

### PR DESCRIPTION
**Pull request by mkoeppe**
Preview at https://github.com/mkoeppe/SCIP-SDP/actions/runs/3660649526

### CODE REVIEW

**Comment by pfetsch** [comment]
Sorry, I have not seen this until now.
Do I understand this correctly: After merging, the Sage CI will automatically run on this repository?

**Comment by mkoeppe** [comment]
> Do I understand this correctly: After merging, the Sage CI will automatically run on this repository?

Yes. It's configurable on what events it runs - see `on:`

**Comment by pfetsch** [comment]
Cool. I will try this soon with new commits ...

**Comment by pfetsch** [comment]
There are errors that I do not understand. @mkoeppe Can you have a look at the actions?

**Pull request merged**
