### PR TITLE
ci-sage.yml: Test with SCIP 9

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by pfetsch** [comment]
Do you understand why the build fails? I do not see any particular error message in the logs.

**Comment by mkoeppe** [comment]
You can see it in the section "Print out logs for immediate inspection".
For example https://github.com/scipopt/SCIP-SDP/actions/runs/8075867433/job/22063419204?pr=13#step:14:3815
shows that it's what I reported in #12

**Comment by mkoeppe** [comment]
Force-pushed to trigger another run, which will pick up the latest version of https://github.com/sagemath/sage/pull/37494 including your fix from https://github.com/scipopt/SCIP-SDP/issues/12#issuecomment-1969453709

**Comment by mkoeppe** [comment]
In the meantime, I have added the update of Soplex to 7.0.0 to https://github.com/sagemath/sage/pull/37494
There are now lots of failures, I've opened https://github.com/scipopt/soplex/issues/35 for this.

**Comment by mkoeppe** [comment]
Test failures on all macOS platforms
```
 [scip_sdp-git]       Start 1: applications-scipsdp-build
  [scip_sdp-git]   1/7 Test #1: applications-scipsdp-build .......   Passed    0.26 sec
  [scip_sdp-git]       Start 2: scipsdp-example_small.dat-s
  [scip_sdp-git]   2/7 Test #2: scipsdp-example_small.dat-s ......Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]       Start 3: scipsdp-example_small_cbf.cbf
  [scip_sdp-git]   3/7 Test #3: scipsdp-example_small_cbf.cbf ....Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]       Start 4: scipsdp-example_inf.dat-s
  [scip_sdp-git]   4/7 Test #4: scipsdp-example_inf.dat-s ........Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]       Start 5: scipsdp-example_TT.dat-s.gz
  [scip_sdp-git]   5/7 Test #5: scipsdp-example_TT.dat-s.gz ......Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]       Start 6: scipsdp-example_CLS.dat-s.gz
  [scip_sdp-git]   6/7 Test #6: scipsdp-example_CLS.dat-s.gz .....Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]       Start 7: scipsdp-example_MkP.dat-s.gz
  [scip_sdp-git]   7/7 Test #7: scipsdp-example_MkP.dat-s.gz .....Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]   
  [scip_sdp-git]   14% tests passed, 6 tests failed out of 7
  [scip_sdp-git]   
  [scip_sdp-git]   Total Test time (real) =   0.29 sec
  [scip_sdp-git]   
  [scip_sdp-git]   The following tests FAILED:
  [scip_sdp-git]   	  2 - scipsdp-example_small.dat-s (Subprocess aborted)
  [scip_sdp-git]   	  3 - scipsdp-example_small_cbf.cbf (Subprocess aborted)
  [scip_sdp-git]   	  4 - scipsdp-example_inf.dat-s (Subprocess aborted)
  [scip_sdp-git]   	  5 - scipsdp-example_TT.dat-s.gz (Subprocess aborted)
  [scip_sdp-git]   	  6 - scipsdp-example_CLS.dat-s.gz (Subprocess aborted)
  [scip_sdp-git]   	  7 - scipsdp-example_MkP.dat-s.gz (Subprocess aborted)
  [scip_sdp-git]   Errors while running CTest
  [scip_sdp-git]   Output from these tests are in: /Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard/local/var/tmp/sage/build/scip_sdp-git/src/build/Testing/Temporary/LastTest.log
  [scip_sdp-git]   Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
  [scip_sdp-git]   make[3]: *** [test] Error 8
```

**Comment by pfetsch** [comment]
Do I see this correctly that there is a problem with installing Soplex and this leads to the fails?

Unfortunately, I do not find enough information in the logs about the failure. Can I actually see the output of SCIP-SDP?

**Comment by mkoeppe** [comment]
> Do I see this correctly that there is a problem with installing Soplex and this leads to the fails?

No, I made it "scip" across the soplex failures in 3c44305.

**Comment by mkoeppe** [comment]
Link to the scipsdp failures: https://github.com/scipopt/SCIP-SDP/actions/runs/8101387931/job/22141465862?pr=13#step:13:2971

**Comment by pfetsch** [comment]
The given output only contains the summary of the tests, but not the output of SCIP-SDP itself. The log file says that the output of SCIP-SDP is available at `/Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard/local/var/tmp/sage/build/scip_sdp-git/src/build/Testing/Temporary/LastTest.log`. I don't think that I can access this file through github.

**Comment by mkoeppe** [comment]
The output says `Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.`
Where should I put these switches?

**Comment by mkoeppe** [comment]
log artifacts can be found on the workflow run's Summary page: https://github.com/scipopt/SCIP-SDP/actions/runs/8101387931?pr=13

**Comment by mkoeppe** [comment]
For example [logs-commit-5e2deaf6e15eed87a1731e412a5eb44f450ae2d1-tox-local-homebrew-macos-usrlocal-standard-macos-13-xcode_15.0](https://github.com/scipopt/SCIP-SDP/actions/runs/8101387931/artifacts/1287540528)

**Comment by pfetsch** [comment]
I seems that they are command line arguments to `ctest`. I cannot find a `ctest` call in `ci-sage.yml`.  Is this contained in some Sage files?

**Comment by mkoeppe** [comment]
This is the script used for testing:
https://github.com/mkoeppe/sage/blob/scip_9/build/pkgs/scip_sdp/spkg-check.in

**Comment by mkoeppe** [comment]
> The log file says that the output of SCIP-SDP is available at `/Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard/local/var/tmp/sage/build/scip_sdp-git/src/build/Testing/Temporary/LastTest.log`. I don't think that I can access this file through github.

Confirmed, there is no way to access it at the moment.

**Comment by pfetsch** [comment]
> This is the script used for testing: https://github.com/mkoeppe/sage/blob/scip_9/build/pkgs/scip_sdp/spkg-check.in

I think that you can replace 
```
$MAKE test
```
by
```
ctest --rerun-failed --output-on-failure
```

**Comment by mkoeppe** [comment]
OK, I've added this in https://github.com/sagemath/sage/pull/37494/commits/b76407e4fbccd28f30a6686223bdee51dff47c4f

**Comment by mkoeppe** [comment]
> > The log file says that the output of SCIP-SDP is available at `/Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard/local/var/tmp/sage/build/scip_sdp-git/src/build/Testing/Temporary/LastTest.log`. I don't think that I can access this file through github.
> 
> Confirmed, there is no way to access it at the moment.

The run just started will fix this

**Comment by mkoeppe** [comment]
OK, now there's more output.
```
  [scip_sdp-git]       Start 6: scipsdp-example_CLS.dat-s.gz
  [scip_sdp-git]   5/6 Test #6: scipsdp-example_CLS.dat-s.gz .....Subprocess aborted***Exception:   0.00 sec
  [scip_sdp-git]   dyld[6803]: Library not loaded: libscip.9.0.dylib
  [scip_sdp-git]     Referenced from: <72534770-3906-3373-A088-E351AD280AF3> /Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard-xcode_15.0/local/var/tmp/sage/build/scip_sdp-git/src/build/bin/scipsdp
  [scip_sdp-git]     Reason: tried: 'libscip.9.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibscip.9.0.dylib' (no such file), 'libscip.9.0.dylib' (no such file), '/Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard-xcode_15.0/local/var/tmp/sage/build/scip_sdp-git/src/build/libscip.9.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard-xcode_15.0/local/var/tmp/sage/build/scip_sdp-git/src/build/libscip.9.0.dylib' (no such file), '/Users/runner/work/SCIP-SDP/SCIP-SDP/.tox/local-homebrew-macos-usrlocal-standard-xcode_15.0/local/var/tmp/sage/build/scip_sdp-git/src/build/libscip.9.0.dylib' (no such file)
```
https://github.com/scipopt/SCIP-SDP/actions/runs/8132023428/job/22221998095?pr=13#step:10:2724

Looks like I need to check if I need to reapply some of my build patches for rpath-like things on macOS

**Comment by mkoeppe** [comment]
Restarted so it picks up https://github.com/sagemath/sage/pull/37494/commits/1b95968aa945727bfad4f63ef36d704c34f61a7b

**Comment by mkoeppe** [comment]
OK, it's all good.

**Comment by pfetsch** [comment]
Very good - so we can merge?

**Comment by mkoeppe** [comment]
Yes, please go ahead

**Pull request merged**
