### PR TITLE
.github/workflows/ci-sage.yml: Update after SageMath's move to GitHub

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes https://github.com/scipopt/SCIP-SDP/pull/4#issuecomment-1574939863

Manually triggered test run: https://github.com/mkoeppe/SCIP-SDP/actions/runs/5194662758
(the tests now fail because another one of our patches is incompatible with the changes in SCIP-SDP - see https://github.com/mkoeppe/SCIP-SDP/actions/runs/5194662758/jobs/9366583370#step:10:5123 .)

### CODE REVIEW

**Comment by pfetsch** [comment]
Thanks for the fixes.

I think that the patches are old - or at least they should be incorporated. If not, I should include them here.

How can I remove multiple patches in the "REMOVE_PATCHES" line in the yml file?

**Comment by mkoeppe** [comment]
> How can I remove multiple patches in the "REMOVE_PATCHES" line in the yml file?

Everything in the quotes just becomes part of a command-line of `rm -f ....`. So use whitespace-separated lists of files: "findlapack-09e79cf75146ca34c637f919d1f4527a63743300.patch abcdefg.patch" or any glob patterns like: "*"

**Comment by mkoeppe** [comment]
> I think that the patches are old - or at least they should be incorporated.

Not sure if I sent all of them to you via PR. The patches are at https://github.com/sagemath/sage/tree/develop/build/pkgs/scip_sdp/patches
In particular, not sure if I sent you the rpath patch

**Comment by pfetsch** [comment]
Thanks. I will check the rpath patch.

**Comment by pfetsch** [comment]
I check all the patches and they should be included.

The current errors all seem to happen because `TBB` does not install correctly.

**Comment by mkoeppe** [comment]
Right, `tbb` and also `openblas` on some platforms (known issue). 
I'll look into upgrading our tbb package. Tests running at https://github.com/mkoeppe/SCIP-SDP/actions/runs/5298512526

**Pull request merged**
